### ISSUE TITLE
Consider adding a tox.ini file?

### ISSUE THREAD

**Issue by noahp** [memfault/gdbundle#1]
There are a large number of python versions specified in the classifiers:
https://github.com/memfault/gdbundle/blob/master/pyproject.toml#L13-L19

For sanity it might be nice to have a tox.ini to run through them all :grinning: 

It can be challenging to support multiple python versions on the host; my go-to method is pyenv for these situations, enclosed in a Dockerfile for CI immunity. That gives you access to a LOT of python versions for cheap.

Especially fond of this for easing the pyenv-tox interface:
https://pypi.org/project/tox-pyenv/

**Comment by tyhoff** [comment]
I'm honestly not sure if Tox can help here. Here's what I think we need: 

- I'd like to test installing packages into Python 2.7, and 3.5+
- I'd like to test Python2.7 against a GDB compiled with 2.7
- I'd like to test each Python 3.5+ against it's equal GDB with Python installed. 
- I'd like to do the same as above, but with LLDB as well. 

I believe the easiest way to get GDB and LLDB linked with an appropriate Python is to use Conda. Maybe [conda-tox](https://github.com/tox-dev/tox-conda) will work for this use-case though. 

https://anaconda.org/conda-forge/gdb
https://anaconda.org/conda-forge/lldb

Not sure how easy it would be to build gdb for each of the Pythons, but that is also an option (so that we can use pyenv).

**Comment by noahp** [comment]
Makes sense, I had kinda forgotten about how this all needs to run in the gdb-python baked in interpreter :grimacing: . Conda approach seems reasonable, another option would be little dockerfiles for each combo, of which I think these are the unique environments needed:

- python{2.7,3.5,3.6,3.7,3.8...3.9? 3.10?} + (arm-none-eabi-?)gdb-py-{same python} + lldb-py-{same python}

The nice thing about using docker is less host influence, and maybe easier development usage? :shrug: . Unfortunately the pre packaged versions of gdb/lldb available on conda only seem to go back to 7.1, so we'd need to publish old versions, or use old versions of debian/ubuntu docker base images to hit the correct builtin python versions for everybody. For what it's worth, on my Ubuntu 20.04 system:

```bash
❯ ldd =gdb | rg python
        libpython3.8.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (0x00007f1cdd0a2000)

❯ ldd =lldb-9 | rg python
        libpython3.8.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (0x00007f55d8580000)
```

There's also packages for lldb-6 through 8, so maybe those have other pythons?

**Comment by franc0is** [comment]
I really dislike docker for development environment. If you're on non-linux hosts the resource & disk usage is nuts.

**Comment by tyhoff** [comment]
Done!
